<a href="https://colab.research.google.com/github/danish-khan962/Deep-Learning/blob/main/01_tensorflow_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# This notebook covers some of the most fundamental concepts of tensors using TensorFlow
## This is the starting of Deep Learning journey....

Most specifically, we're going to cover:
* Introduction to tensors
* Getting Information from tensors
* Manipulating tensors
* Tensors && Numpy
* Using @tf.function(a way to speed up regular Python functions)
* Using GPUs with TensorFlow (or TPUs)

# 1. Introduction to Tensors

In [1]:
#Import TensorFlow
import tensorflow as tf
print(tf.__version__)

2.18.0


In [2]:
#Creating tensors with tf.constant()
scalar = tf.constant(9)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=9>

In [3]:
#Checking the number of dimensions of a tensor
scalar.ndim

0

In [4]:
# Creating a vector
vector = tf.constant([10,15])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 15], dtype=int32)>

In [5]:
vector.ndim

1

In [6]:
#Create a matrix (has more than 1 dimensions)
matrix = tf.constant([[20,5],
                      [3,7]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20,  5],
       [ 3,  7]], dtype=int32)>

In [7]:
matrix.ndim

2

In [8]:
#Create another matrix
another_matrix = tf.constant([[5., 7.],
                              [6., 8.],
                              [7., 4.]], dtype = tf.float16)
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[5., 7.],
       [6., 8.],
       [7., 4.]], dtype=float16)>

In [9]:
#Number of dimensions of another_matrix
another_matrix.ndim

2

In [10]:
# Let's create a tensor
tensor = tf.constant([[[1, 2, 3],
                       [4, 5, 6]],
                      [[7, 8, 9],
                       [10, 11, 12]],
                      [[13, 14, 15],
                       [16, 17, 18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [11]:
tensor.ndim

3

# What we've created so far

* `Scalar:` a single number
* `Vector:` a number with direction(e.g., wind speed & direction)
* `Matrix:` a 2-dimensional array of numbers
* `Tensor:` an n-dimesnional array of numbers(where `n` can be any number, a 0-Dimensional tensor is a scalar, a 1-Dimensional tensor is a vector)

### Creating tensors with `tf.Variable`

In [12]:
tf.Variable

tensorflow.python.ops.variables.Variable

In [13]:
# Let's play with changable and unchangeable tensors
changeable_tensors = tf.Variable([5,9])
unchangeable_tensor = tf.constant([7,3])
changeable_tensors , unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([5, 9], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 3], dtype=int32)>)

In [14]:
# Let's try to change value in changeable tensor
changeable_tensors[0] = 9    #Let's try to assign 9 onto 0th index
changeable_tensors

TypeError: 'ResourceVariable' object does not support item assignment

In [15]:
# Oops! we got error in assingning
# How about using .assing method available in tensorflow
changeable_tensors[0].assign(9)
changeable_tensors

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([9, 9], dtype=int32)>

In [16]:
# Now, let's try to change value in unchangeable tensor
unchangeable_tensor[0].assign(3)
unchangeable_tensor

AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'assign'

`📜Note` : When we want tensors which change their values we use `tf.Variable()`, and when we want such tensors which do not change their values we use `tf.constant()`

### Creating random tensors

Random tensors are tensors of some arbitary size which contains random numbers.

In [17]:
# Create two random (but the same) tensors
random_1 = tf.random.Generator.from_seed(42) # set seed for reproducibility
random_1 = random_1.normal(shape=(3,2))
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape=(3,2))

In [18]:
random_1, random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>)

In [19]:
random_1 == random_2

<tf.Tensor: shape=(3, 2), dtype=bool, numpy=
array([[ True,  True],
       [ True,  True],
       [ True,  True]])>

### Shuffle the order of elements in tensor

#####  `What is the need of shuffling tensors?`
#####  e.g., Suppose you have total of 10,000 images in which 8,000 are of dogs and rest 2,000 are of cats.
#####        When our neural network will hit the tensors it will learn the pattern of only dogs most probably as it can't see cats for a long time.
#####        This may affect the results and accuracy, hence shuffling of tensors is necessary


In [20]:
# Shuffle a tensor (valubale for when you want to shuffle your data so that inherent order doesn't effect learning)
not_shuffled_tensor = tf.constant([[1,2],
                                   [3,4],
                                   [5,6]])
not_shuffled_tensor.ndim

2

In [21]:
not_shuffled_tensor

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [5, 6]], dtype=int32)>

It looks like if we want our shuffled tensors to be in the same order, we've got to use the global level random seed as well as the operational level random seed:

> `Rule 4`: If both the global and the operatinal seed are set: Both seeds are used in conjunction to determine the random sequence

In [22]:
#shuffling our not_shuffled_tensor
tf.random.set_seed(42)
tf.random.shuffle(not_shuffled_tensor, seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [5, 6]], dtype=int32)>

### Other ways to create tensors

In [23]:
# Create a tensor with all elements as 1
tf.ones([5,6])

<tf.Tensor: shape=(5, 6), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [24]:
# Create a tensor with all elements as 0
tf.zeros([5,6])

<tf.Tensor: shape=(5, 6), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]], dtype=float32)>

### Turn Numpy arrays into tensors

The main difference between Numpy arrays and TensorFlow tensors is that tensors can be run on a GPU much faster(for numerical computing)

In [25]:
# We can also create NumPy arrays into tensors
import numpy as np
np_arr = np.arange(1,31, dtype=np.int32)

# X = tf.constant(some_matrix)   # capital for matrix or tensor
# y = tf.constant(vector)  # non-capital for vector

np_arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30], dtype=int32)

In [26]:
# converting numpy array -> tensor
A = tf.constant(np_arr, shape=(5,6))
A

<tf.Tensor: shape=(5, 6), dtype=int32, numpy=
array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]], dtype=int32)>

In [27]:
5 * 6 #it should be 30(total elements) then will `shape` work

30

### Getting Information from tensors

When dealing with tensors we probably want to aware of the following attributes:
* Shape
* Rank
* Axis and dimension
* Size

In [28]:
# Create a rank 4 tensor (4 dimensions)
rank_4_tensor = tf.zeros(shape=[2,3,4,5])
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [29]:
rank_4_tensor[0]

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)>

In [30]:
print("Shape of tensor: ",rank_4_tensor.shape)
print("Rank of tensor: ", rank_4_tensor.ndim)
print("Size of tensor: ", tf.size(rank_4_tensor))

Shape of tensor:  (2, 3, 4, 5)
Rank of tensor:  4
Size of tensor:  tf.Tensor(120, shape=(), dtype=int32)


In [31]:
2 * 3 * 4 * 5

120

In [32]:
# Get various attributes of our tensor
print("Datatype of every element: ", rank_4_tensor.dtype)
print("Number of dimensions (rank): ", rank_4_tensor.ndim)
print("Shape of tensor: ",rank_4_tensor.shape)
print("Elements along the 0 axis: ", rank_4_tensor.shape[0])
print("Elements along the last axis: ", rank_4_tensor.shape[-1])
print("Total number of elements in our tensor: ", tf.size(rank_4_tensor).numpy())

Datatype of every element:  <dtype: 'float32'>
Number of dimensions (rank):  4
Shape of tensor:  (2, 3, 4, 5)
Elements along the 0 axis:  2
Elements along the last axis:  5
Total number of elements in our tensor:  120


### Indexing tensors

Tensors can be indexed just like python lists

In [33]:
# Get the first 2 elements of each dimensions
rank_4_tensor[:2, :2, :2, :2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [34]:
# Get first element frome each dimension from each index except for final one
rank_4_tensor[:1, :1, :1, :]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [35]:
# Create a rank 2 tensor (2 dimensions)
rank_2_tensor = tf.zeros([2,4])
rank_2_tensor

<tf.Tensor: shape=(2, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

In [36]:
rank_2_tensor.ndim

2

In [37]:
# Get the last item of each row of our rank_2_tensor
rank_2_tensor[:, -1]

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([0., 0.], dtype=float32)>

In [38]:
# Add in extra dimension to our rank_2_tensor
rank_3_tensor = rank_2_tensor[..., tf.newaxis]     # ... means creating a copy
rank_3_tensor

<tf.Tensor: shape=(2, 4, 1), dtype=float32, numpy=
array([[[0.],
        [0.],
        [0.],
        [0.]],

       [[0.],
        [0.],
        [0.],
        [0.]]], dtype=float32)>

In [39]:
# Alternative to tf.newaxis
tf.expand_dims(rank_2_tensor, axis=-1)  # -1 means expannd the final axis

<tf.Tensor: shape=(2, 4, 1), dtype=float32, numpy=
array([[[0.],
        [0.],
        [0.],
        [0.]],

       [[0.],
        [0.],
        [0.],
        [0.]]], dtype=float32)>

### Manipulating Tensors (tensor operations)

**Basic Operations**
`+`, `-`, `*`, `/`

In [40]:
# You can add values to a tensor using the addition operator
tensor = tf.constant([[2,4], [5,4]])
tensor + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[12, 14],
       [15, 14]], dtype=int32)>

In [41]:
# Remember : Original tensor is unchanged
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[2, 4],
       [5, 4]], dtype=int32)>

In [42]:
# Multiplication
tensor * 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 40],
       [50, 40]], dtype=int32)>

In [43]:
# Subtraction
tensor - 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[-8, -6],
       [-5, -6]], dtype=int32)>

In [44]:
# Divison
tensor / 10

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[0.2, 0.4],
       [0.5, 0.4]])>

In [45]:
# We can use the tensorflow built-in function too
tf.multiply(tensor, 10)  # this will do element wise multiplication

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 40],
       [50, 40]], dtype=int32)>

### Matrix Multiplication

In machine learning, matrix multiplication is one of the most common tensor operations


There are two rules our tensors (or matrices) need to fulfil if we're going to matrix multiply them:

1. The inner dimensions must match
2. The resulting matrix has the shape of the outer dimensions

In [46]:
 # Matrix multiplication in tensorflow
print(tensor)
tf.matmul(tensor, tensor)

tf.Tensor(
[[2 4]
 [5 4]], shape=(2, 2), dtype=int32)


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[24, 24],
       [30, 36]], dtype=int32)>

In [47]:
# Another example of matrix multiplication in tensor
t1 = tf.constant([[1,2,5],
                  [7,2,1],
                  [3,3,3]])
t2 = tf.constant([[3,5],
                  [6,7],
                  [1,8]])
print(t1)
print(t2)

print("Matrix multiplication by tensorflow...")
tf.matmul(t1, t2)

tf.Tensor(
[[1 2 5]
 [7 2 1]
 [3 3 3]], shape=(3, 3), dtype=int32)
tf.Tensor(
[[3 5]
 [6 7]
 [1 8]], shape=(3, 2), dtype=int32)
Matrix multiplication by tensorflow...


<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[20, 59],
       [34, 57],
       [30, 60]], dtype=int32)>

In [48]:
# Mtarix multiplication with Python operator "@"
t1 @ t2

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[20, 59],
       [34, 57],
       [30, 60]], dtype=int32)>

In [49]:
t1.shape, t2.shape

(TensorShape([3, 3]), TensorShape([3, 2]))

In [50]:
# Trying matrix multiplication by tensorflow of shame shapes
t3 = tf.constant([[1,2],
                  [2,3],
                  [3,4]])
t4 = tf.constant([[4,5],
                  [5,6],
                  [6,7]])
print("Shape of t3: ", t3.shape)
print("Shape of t4: ", t4.shape)

#  tf.matmul(t3, t4)    # it will throw error here because inner dimensions are not same

# try to multiply t3 with reshaped t4
t3 @ tf.reshape(t4, shape=(2,3))

# trying matmul
tf.matmul(t3, tf.reshape(t4, shape=(2,3)))

Shape of t3:  (3, 2)
Shape of t4:  (3, 2)


<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[16, 17, 19],
       [26, 28, 31],
       [36, 39, 43]], dtype=int32)>

In [51]:
# Can to the same with transpose
t3, tf.transpose(t3), tf.reshape(t3, shape=(2,3))

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [2, 3],
        [3, 4]], dtype=int32)>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 2, 3],
        [2, 3, 4]], dtype=int32)>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 2, 2],
        [3, 3, 4]], dtype=int32)>)

In [52]:
# Trying matrix multiplication with transpose rahter than reshape
tf.matmul(tf.transpose(t3), t4)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[32, 38],
       [47, 56]], dtype=int32)>

**Dot Product**

Matrix multiplication is also referred to as the dot product.

You can perform matrix multiplication using:
* `tf.matmul()`
* `tf.tensordot()`
* `@`

In [53]:
# Perform the dot product on X and Y (requires X or Y to be transposed)
X = tf.constant([[1,2],
                 [3,4],
                 [5,6]])
Y = tf.constant([[7,8],
                 [9,10],
                 [11,12]])

In [54]:
X, Y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32)>)

In [56]:
tf.tensordot(tf.transpose(X), Y, axes=1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

In [57]:
# Perform matrix multiplication between X and Y (transposed)
tf.matmul(X, tf.transpose(Y))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  29,  35],
       [ 53,  67,  81],
       [ 83, 105, 127]], dtype=int32)>

In [58]:
# Perform matrix multiplication between X and Y (reshaped)
tf.matmul(X, tf.reshape(Y, shape=(2,3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [60]:
# Check the values of Y, reshape Y and transposed Y
print("Normal Y: ")
print(Y, "\n")

print("Y reshaped to (2,3): ")
print(tf.reshape(Y, (2,3)), "\n")

print("Y transposed: ")
print(tf.transpose(Y))

Normal Y: 
tf.Tensor(
[[ 7  8]
 [ 9 10]
 [11 12]], shape=(3, 2), dtype=int32) 

Y reshaped to (2,3): 
tf.Tensor(
[[ 7  8  9]
 [10 11 12]], shape=(2, 3), dtype=int32) 

Y transposed: 
tf.Tensor(
[[ 7  9 11]
 [ 8 10 12]], shape=(2, 3), dtype=int32)


In [64]:
tf.matmul(X, tf.transpose(Y))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  29,  35],
       [ 53,  67,  81],
       [ 83, 105, 127]], dtype=int32)>

Generally, when performing matrix multiplication on two tensors and one of the axes doesn't line up, you will transpose(rather than reshape) one of the tesnors to get satisfy the matrix multiplication rules.

### Changing the datatype of a tensor