<a href="https://colab.research.google.com/github/danish-khan962/Deep-Learning/blob/main/01_tensorflow_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# This notebook covers some of the most fundamental concepts of tensors using TensorFlow
## This is the starting of Deep Learning journey....

Most specifically, we're going to cover:
* Introduction to tensors
* Getting Information from tensors
* Manipulating tensors
* Tensors && Numpy
* Using @tf.function(a way to speed up regular Python functions)
* Using GPUs with TensorFlow (or TPUs)

# 1. Introduction to Tensors

In [28]:
#Import TensorFlow
import tensorflow as tf
print(tf.__version__)

2.18.0


In [29]:
#Creating tensors with tf.constant()
scalar = tf.constant(9)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=9>

In [30]:
#Checking the number of dimensions of a tensor
scalar.ndim

0

In [31]:
# Creating a vector
vector = tf.constant([10,15])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 15], dtype=int32)>

In [32]:
vector.ndim

1

In [33]:
#Create a matrix (has more than 1 dimensions)
matrix = tf.constant([[20,5],
                      [3,7]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20,  5],
       [ 3,  7]], dtype=int32)>

In [34]:
matrix.ndim

2

In [35]:
#Create another matrix
another_matrix = tf.constant([[5., 7.],
                              [6., 8.],
                              [7., 4.]], dtype = tf.float16)
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[5., 7.],
       [6., 8.],
       [7., 4.]], dtype=float16)>

In [36]:
#Number of dimensions of another_matrix
another_matrix.ndim

2

In [37]:
# Let's create a tensor
tensor = tf.constant([[[1, 2, 3],
                       [4, 5, 6]],
                      [[7, 8, 9],
                       [10, 11, 12]],
                      [[13, 14, 15],
                       [16, 17, 18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [38]:
tensor.ndim

3

# What we've created so far

* `Scalar:` a single number
* `Vector:` a number with direction(e.g., wind speed & direction)
* `Matrix:` a 2-dimensional array of numbers
* `Tensor:` an n-dimesnional array of numbers(where `n` can be any number, a 0-Dimensional tensor is a scalar, a 1-Dimensional tensor is a vector)

### Creating tensors with `tf.Variable`

In [39]:
tf.Variable

tensorflow.python.ops.variables.Variable

In [40]:
# Let's play with changable and unchangeable tensors
changeable_tensors = tf.Variable([5,9])
unchangeable_tensor = tf.constant([7,3])
changeable_tensors , unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([5, 9], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 3], dtype=int32)>)

In [42]:
# Let's try to change value in changeable tensor
changeable_tensors[0] = 9    #Let's try to assign 9 onto 0th index
changeable_tensors

TypeError: 'ResourceVariable' object does not support item assignment

In [43]:
# Oops! we got error in assingning
# How about using .assing method available in tensorflow
changeable_tensors[0].assign(9)
changeable_tensors

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([9, 9], dtype=int32)>

In [44]:
# Now, let's try to change value in unchangeable tensor
unchangeable_tensor[0].assign(3)
unchangeable_tensor

AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'assign'

`📜Note` : When we want tensors which change their values we use `tf.Variable()`, and when we want such tensors which do not change their values we use `tf.constant()`

### Creating random tensors

Random tensors are tensors of some arbitary size which contains random numbers.

In [45]:
# Create two random (but the same) tensors
random_1 = tf.random.Generator.from_seed(42) # set seed for reproducibility
random_1 = random_1.normal(shape=(3,2))
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape=(3,2))

In [46]:
random_1, random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>)

In [47]:
random_1 == random_2

<tf.Tensor: shape=(3, 2), dtype=bool, numpy=
array([[ True,  True],
       [ True,  True],
       [ True,  True]])>

### Shuffle the order of elements in tensor

#####  `What is the need of shuffling tensors?`
#####  e.g., Suppose you have total of 10,000 images in which 8,000 are of dogs and rest 2,000 are of cats.
#####        When our neural network will hit the tensors it will learn the pattern of only dogs most probably as it can't see cats for a long time.
#####        This may affect the results and accuracy, hence shuffling of tensors is necessary


In [48]:
# Shuffle a tensor (valubale for when you want to shuffle your data so that inherent order doesn't effect learning)
not_shuffled_tensor = tf.constant([[1,2],
                                   [3,4],
                                   [5,6]])
not_shuffled_tensor.ndim

2

In [49]:
not_shuffled_tensor

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [5, 6]], dtype=int32)>

It looks like if we want our shuffled tensors to be in the same order, we've got to use the global level random seed as well as the operational level random seed:

> `Rule 4`: If both the global and the operatinal seed are set: Both seeds are used in conjunction to determine the random sequence

In [50]:
#shuffling our not_shuffled_tensor
tf.random.set_seed(42)
tf.random.shuffle(not_shuffled_tensor, seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [5, 6]], dtype=int32)>

### Other ways to create tensors

In [51]:
# Create a tensor with all elements as 1
tf.ones([5,6])

<tf.Tensor: shape=(5, 6), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [52]:
# Create a tensor with all elements as 0
tf.zeros([5,6])

<tf.Tensor: shape=(5, 6), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]], dtype=float32)>

### Turn Numpy arrays into tensors

The main difference between Numpy arrays and TensorFlow tensors is that tensors can be run on a GPU much faster(for numerical computing)

In [53]:
# We can also create NumPy arrays into tensors
import numpy as np
np_arr = np.arange(1,31, dtype=np.int32)

# X = tf.constant(some_matrix)   # capital for matrix or tensor
# y = tf.constant(vector)  # non-capital for vector

np_arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30], dtype=int32)

In [54]:
# converting numpy array -> tensor
A = tf.constant(np_arr, shape=(5,6))
A

<tf.Tensor: shape=(5, 6), dtype=int32, numpy=
array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]], dtype=int32)>

In [55]:
5 * 6 #it should be 30(total elements) then will `shape` work

30

### Getting Information from tensors

When dealing with tensors we probably want to aware of the following attributes:
* Shape
* Rank
* Axis and dimension
* Size

In [57]:
# Create a rank 4 tensor (4 dimensions)
rank_4_tensor = tf.zeros(shape=[2,3,4,5])
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [60]:
rank_4_tensor[0]

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)>

In [63]:
print("Shape of tensor: ",rank_4_tensor.shape)
print("Rank of tensor: ", rank_4_tensor.ndim)
print("Size of tensor: ", tf.size(rank_4_tensor))

Shape of tensor:  (2, 3, 4, 5)
Rank of tensor:  4
Size of tensor:  tf.Tensor(120, shape=(), dtype=int32)


In [64]:
2 * 3 * 4 * 5

120

In [66]:
# Get various attributes of our tensor
print("Datatype of every element: ", rank_4_tensor.dtype)
print("Number of dimensions (rank): ", rank_4_tensor.ndim)
print("Shape of tensor: ",rank_4_tensor.shape)
print("Elements along the 0 axis: ", rank_4_tensor.shape[0])
print("Elements along the last axis: ", rank_4_tensor.shape[-1])
print("Total number of elements in our tensor: ", tf.size(rank_4_tensor).numpy())

Datatype of every element:  <dtype: 'float32'>
Number of dimensions (rank):  4
Shape of tensor:  (2, 3, 4, 5)
Elements along the 0 axis:  2
Elements along the last axis:  5
Total number of elements in our tensor:  120
