<a href="https://colab.research.google.com/github/danish-khan962/Deep-Learning/blob/main/miscellaneous/01_excercise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **EXCERCISE 01**

###### Read through the documentation on random seed generation:
###### https://www.tensorflow.org/api_docs/python/tf/random/set_seed and practice writing 5 random tensors and shuffle them

In [ ]:
# Importing Tensorflow
import tensorflow as tf
print("Tensorflow version we're using: ", tf.__version__)

Tensorflow version we're using:  2.18.0


### Creating random tensors

In [ ]:
# Creating 5 random tensors
randomTensor_1 = tf.random.Generator.from_seed(45) #setting seed for reproducability
randomTensor_1 = randomTensor_1.normal(shape=(3,3))

randomTensor_2 = tf.random.Generator.from_seed(42)
randomTensor_2 = randomTensor_2.normal(shape=(3,3))

randomTensor_3 = tf.random.Generator.from_seed(45)
randomTensor_3 = randomTensor_3.normal(shape=(3,3))

randomTensor_4 = tf.random.Generator.from_seed(42)
randomTensor_4 = randomTensor_4.normal(shape=(3,3))

randomTensor_5 = tf.random.Generator.from_seed(45)
randomTensor_5 = randomTensor_5.normal(shape=(3,3))

In [ ]:
# Checking how our random tensors looks like
randomTensor_1 , randomTensor_2 , randomTensor_3 , randomTensor_4 , randomTensor_5

(<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
 array([[-0.3522796 ,  0.40621263, -1.0523509 ],
        [ 1.2054597 ,  1.6874489 , -0.4462975 ],
        [-2.3410842 ,  0.99009085, -0.0876323 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 3), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702,  0.07595026],
        [-1.2573844 , -0.23193763, -1.8107855 ],
        [ 0.09988727, -0.50998646, -0.7535805 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 3), dtype=float32, numpy=
 array([[-0.3522796 ,  0.40621263, -1.0523509 ],
        [ 1.2054597 ,  1.6874489 , -0.4462975 ],
        [-2.3410842 ,  0.99009085, -0.0876323 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 3), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702,  0.07595026],
        [-1.2573844 , -0.23193763, -1.8107855 ],
        [ 0.09988727, -0.50998646, -0.7535805 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 3), dtype=float32, numpy=
 array([[-0.3522796 ,  0.40621263, -1.0523509 ],
        [ 1.2054597 ,  1.6874489 , -0.4462975 

### Shuffling a random tensor

In [ ]:
# Let's again create a random tensor for shuffling

non_shuffledTensor = tf.random.Generator.from_seed(30)
non_shuffledTensor = non_shuffledTensor.normal(shape=(5,2))

In [ ]:
non_shuffledTensor

<tf.Tensor: shape=(5, 2), dtype=float32, numpy=
array([[ 0.8357487 ,  0.20849545],
       [ 1.4040174 , -2.735283  ],
       [ 1.2232229 , -1.8653691 ],
       [ 0.00511209, -1.0493753 ],
       [ 0.7901182 ,  1.585549  ]], dtype=float32)>

It looks like if we want our shuffled tensors to be in the same order, we've got to use the global level random seed as well as the operational level random seed:

> `Rule 4`: If both the global and the operatinal seed are set: Both seeds are used in conjunction to determine the random sequence

In [ ]:
# Now shuffling the non_shuffledTensor
tf.random.set_seed(42)  #this is global random seed
tf.random.shuffle(non_shuffledTensor, seed=(42))  #this is operational random seed

<tf.Tensor: shape=(5, 2), dtype=float32, numpy=
array([[ 0.00511209, -1.0493753 ],
       [ 0.8357487 ,  0.20849545],
       [ 1.4040174 , -2.735283  ],
       [ 1.2232229 , -1.8653691 ],
       [ 0.7901182 ,  1.585549  ]], dtype=float32)>