<a href="https://colab.research.google.com/github/danish-khan962/Deep-Learning/blob/main/miscellaneous/02_exercise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **EXERCISE 2**
### Create random tensors and gather information from tensors
* shape
* rank
* axis and dimensions
* size

In [1]:
# Importing tensorflow
import tensorflow as tf
print("Tensorflow version we're using: ", tf.__version__)

Tensorflow version we're using:  2.18.0


In [2]:
# Creating random tensors
tensor = tf.random.Generator.from_seed(42)
tensor = tensor.normal(shape=(3,4))
tensor

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702,  0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ,  0.09988727, -0.50998646],
       [-0.7535805 , -0.57166284,  0.1480774 , -0.23362993]],
      dtype=float32)>

In [6]:
# Gathering information from random tensor
print("Shape of the tensor is : ", tensor.shape)
print("Dimensions (rank) of the tensor is: ", tensor.ndim)
print("Total number of elements in tensor are: ", tf.size(tensor).numpy())

Shape of the tensor is :  (3, 4)
Dimensions (rank) of the tensor is:  2
Total number of elements in tensor are:  12


In [7]:
print("Element along axis 0: ", tensor.shape[0])
print("Element along axis from last: ", tensor.shape[-1])

Element along axis 0:  3
Element along axis from last:  4


In [8]:
3 * 4

12

In [9]:
# Getting first three elements of each dimension
tensor[:3, :3]

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702,  0.07595026],
       [-0.23193763, -1.8107855 ,  0.09988727],
       [-0.7535805 , -0.57166284,  0.1480774 ]], dtype=float32)>

As we have seen above that we have 2 dimension tensor, therefore now will increase it's dimensions by two methods.

> ... spread operator & tf.newaxis

> tf.expand_dims(tensor_name, axis='position')

In [11]:
tensor.ndim

2

In [12]:
# Using first method ...spread operator to increase the number of dimension in tensor
tensor_new = tensor[..., tf.newaxis]
tensor_new

<tf.Tensor: shape=(3, 4, 1), dtype=float32, numpy=
array([[[-0.7565803 ],
        [-0.06854702],
        [ 0.07595026],
        [-1.2573844 ]],

       [[-0.23193763],
        [-1.8107855 ],
        [ 0.09988727],
        [-0.50998646]],

       [[-0.7535805 ],
        [-0.57166284],
        [ 0.1480774 ],
        [-0.23362993]]], dtype=float32)>

In [13]:
tensor_new.ndim

3

In [16]:
# Using second method of tf.expand_dims
T = tf.expand_dims(tensor, axis=0)  # axis works exactly like index, 0 means start and -1 means from end
T

<tf.Tensor: shape=(1, 3, 4), dtype=float32, numpy=
array([[[-0.7565803 , -0.06854702,  0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ,  0.09988727, -0.50998646],
        [-0.7535805 , -0.57166284,  0.1480774 , -0.23362993]]],
      dtype=float32)>

In [17]:
T.ndim

3