<a href="https://colab.research.google.com/github/danish-khan962/Deep-Learning/blob/main/miscellaneous/03_excercise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **EXCERCISE 3**

##### With what we've learned about aggregation tensors, create a random tensor and find the following attributes from that random tenor using Tensorflow methods.

* minimum
* maximum
* mean
* sum
* variance
* standard deviation

In [1]:
# Importing tensorflow
import tensorflow as tf
print("Tensorflow version we're using: ", tf.__version__)

Tensorflow version we're using:  2.18.0


In [2]:
# Creating a random tensor as our test subject

# Creating a tensor with total of 150 random value between -500 and 900 by NumPy
import numpy as np
tensor = tf.constant(np.random.randint(-500, 900, size=150))

In [3]:
# This is how out random tensor looks like
tensor

<tf.Tensor: shape=(150,), dtype=int64, numpy=
array([ 278, -180, -319, -301,  886,   58,  779,  859, -257,  559,  637,
        317, -288,  520,  683,  308,  689,  606, -316, -154,  117,  410,
        578,   22,  144,  282, -149,  751,  889, -151, -225,  755,    2,
        701,  580,  247,  736,  329,   50,  396,  843,  -38, -401,   32,
        197,  875,  212,  875,  863, -155,  356,  154,  708,  564,  328,
        819,  718,  -67, -334,  459, -290, -221,  470,  620, -476,  842,
        109,  -22,  203, -292, -186,  305, -154,  356,  730,  484, -161,
        661, -147, -419,  -29,  108, -228, -282, -377, -420,  500,  109,
        791,  122,  425,   20, -162,  465, -395, -109,  394,   -5,  612,
        842,  189,  825,  606,  168,  -21,  448, -423, -315, -345, -437,
        445,  512,  635, -398, -459, -283,  831,   56,  340,  513,   14,
        364,  345,  625,  282,  132,  359, -357,  675, -151, -247,   21,
        738,  714,  867,  115,  838, -302, -430,  610,   25,  371, -130,
     

In [4]:
# Finding the absolute values of tensor
tf.abs(tensor)

<tf.Tensor: shape=(150,), dtype=int64, numpy=
array([278, 180, 319, 301, 886,  58, 779, 859, 257, 559, 637, 317, 288,
       520, 683, 308, 689, 606, 316, 154, 117, 410, 578,  22, 144, 282,
       149, 751, 889, 151, 225, 755,   2, 701, 580, 247, 736, 329,  50,
       396, 843,  38, 401,  32, 197, 875, 212, 875, 863, 155, 356, 154,
       708, 564, 328, 819, 718,  67, 334, 459, 290, 221, 470, 620, 476,
       842, 109,  22, 203, 292, 186, 305, 154, 356, 730, 484, 161, 661,
       147, 419,  29, 108, 228, 282, 377, 420, 500, 109, 791, 122, 425,
        20, 162, 465, 395, 109, 394,   5, 612, 842, 189, 825, 606, 168,
        21, 448, 423, 315, 345, 437, 445, 512, 635, 398, 459, 283, 831,
        56, 340, 513,  14, 364, 345, 625, 282, 132, 359, 357, 675, 151,
       247,  21, 738, 714, 867, 115, 838, 302, 430, 610,  25, 371, 130,
       390, 396, 184, 515, 296, 388,  40])>

In [5]:
# Finding the minimum value
tf.reduce_min(tensor)

<tf.Tensor: shape=(), dtype=int64, numpy=-476>

In [6]:
# Finding the maximum value
tf.reduce_max(tensor)

<tf.Tensor: shape=(), dtype=int64, numpy=889>

In [7]:
# Finding the mean value
tf.reduce_mean(tensor)

<tf.Tensor: shape=(), dtype=int64, numpy=219>

In [8]:
# Finding the sum
tf.reduce_sum(tensor)

<tf.Tensor: shape=(), dtype=int64, numpy=32963>

In [12]:
# Finding the variance
tf.math.reduce_variance(tensor)

TypeError: Input must be either real or complex. Received integer type <dtype: 'int64'>.

In [13]:
# Oops! Looks like we got an error for finding out int dtype variance
# Let's convert dtype: int64 to dtype: float64
float_tensor = tf.cast(tensor, dtype=np.float64)
float_tensor.dtype

tf.float64

In [15]:
# Now let's try to find out the variance
tf.math.reduce_variance(float_tensor)

<tf.Tensor: shape=(), dtype=float64, numpy=165643.75915555554>

In [17]:
# Finding out standard deviation
tf.math.reduce_std(float_tensor)

<tf.Tensor: shape=(), dtype=float64, numpy=406.993561565236>