<a href="https://colab.research.google.com/github/danish-khan962/Deep-Learning/blob/main/miscellaneous/04_Exercise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **EXERCISE 4**

###### Create a random tensor using tensorflow and try to find the out the positional maximum and minimum of the tensor.

In [1]:
# Importing tensorflow
import tensorflow as tf
print("Tensorflow we're using: ", tf.__version__)

Tensorflow we're using:  2.18.0


In [9]:
# Creating a random tensor
import numpy as np
tf.random.set_seed(42)  # for reproducability
tensor = np.random.randint(100, 15000 , size=100)
tensor

array([ 8370,  6782,   345,  8671,  1994, 12185,  9763, 14267,  2347,
        7104, 14248,  1107,  4159,  2331,  5560,  2818, 11860,  5919,
        3762,  9660,  4001, 13920,  8376, 10777, 12740, 13026, 13599,
       10007,  6467, 14425, 11297,  8142, 12305,   249, 10816, 13791,
        5050,  3325,  2724,  4415, 11299, 12526, 13723, 14193,  6431,
       10685, 12528, 10908,  9776,  7781, 10616,  2208,   290,  4624,
        3476, 14208,  5722,  3873,   124, 12151,  2413, 14554,  9168,
        8951,  8194,  4787,  3569,  8127, 13726, 12734,  3604,   990,
        5665,  9636,  1827,  5582, 11190, 14726,  9099,  4649,  5197,
       11961, 13901,  1496,  9532,  1588, 10963, 14944,   200,  9582,
        5236,  8026,  5513,  7334,  7948,  5991,  4796,   259,  8166,
        9148])

### Positional maximum

In [10]:
# Finding the positional maximum (the index where maximum value exists)
tf.argmax(tensor)

<tf.Tensor: shape=(), dtype=int64, numpy=87>

In [11]:
# Finding out what value exists at positional maximum
tensor[tf.argmax(tensor)]

np.int64(14944)

In [12]:
# Also checking from the max function
tf.reduce_max(tensor)

<tf.Tensor: shape=(), dtype=int64, numpy=14944>

In [13]:
# Verifying if both return the same result
tensor[tf.argmax(tensor)] == tf.reduce_max(tensor)

<tf.Tensor: shape=(), dtype=bool, numpy=True>

### Positional Minimum

In [14]:
# Finding the positional minimum (the index where minimum element exists)
tf.argmin(tensor)

<tf.Tensor: shape=(), dtype=int64, numpy=58>

In [15]:
# Finding out the value of positional minimum
tensor[tf.argmin(tensor)]

np.int64(124)

In [16]:
# Also checking from the min function
tf.reduce_min(tensor)

<tf.Tensor: shape=(), dtype=int64, numpy=124>

In [18]:
# Verifying if both return the same result
tensor[tf.argmin(tensor)] == tf.reduce_min(tensor)

<tf.Tensor: shape=(), dtype=bool, numpy=True>