<a href="https://colab.research.google.com/github/danish-khan962/Deep-Learning/blob/main/miscellaneous/05_exercise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **EXERCISE 5**

##### Create a python list and perform one-hot encoding with custom `on_value` and `off_values`

In [1]:
# Importing tensorflow
import tensorflow as tf
print("Tensorflow version we're using: ", tf.__version__)

Tensorflow version we're using:  2.18.0


In [10]:
# Creating a list
tensor = [0,1,2,3]
tensor

[0, 1, 2, 3]

In [11]:
# Performing one-hot encoding
tf.one_hot(tensor, depth=4)  # depth usually is number of elements

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

### **Custom one-hot encoding**

### on_value and off_value

In [12]:
# Custom on_value and off_value
tf.one_hot(tensor, depth=4, on_value="ON", off_value="OFF")

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'ON', b'OFF', b'OFF', b'OFF'],
       [b'OFF', b'ON', b'OFF', b'OFF'],
       [b'OFF', b'OFF', b'ON', b'OFF'],
       [b'OFF', b'OFF', b'OFF', b'ON']], dtype=object)>